<?php $post ??= ['title' => '', 'client_name' => '', 'category' => '', 'excerpt' => '', 'body' => '', 'services' => [], 'accent' => 'green', 'status' => 'draft', 'featured' => false]; ?>
<main class="desk-layout">
<aside class="desk-sidebar"><div class="sidebar-title"><p class="eyebrow">Story desk</p><h1>Journal studio <span class="count"><?= count($posts) ?></span></h1><a class="button-secondary small" href="<?= e(url('/journal/studio')) ?>">+ New story</a></div>
<?php foreach ($posts as $row): ?><a class="desk-row<?= ($post['id'] ?? null) === $row['id'] ? ' active' : '' ?>" href="<?= e(url('/journal/studio?id=' . $row['id'])) ?>"><span class="row-meta"><?= e($row['client_name']) ?><span class="tag"><?= e($row['status']) ?></span></span><strong><?= e($row['title']) ?></strong><small><?= e($row['category']) ?></small></a><?php endforeach; ?></aside>
<section class="desk-content"><div class="desk-heading"><p class="eyebrow">Business stories and progress</p><h2><?= isset($post['id']) ? 'Edit story' : 'Create a story' ?></h2><p class="muted">Only published stories appear in Tech Stories and Our Work.</p></div>
<?php require __DIR__ . '/_errors.php'; ?><?php if ($feedback): ?><p class="success" role="status"><?= e($feedback) ?></p><?php endif; ?>
<form method="post" action="<?= e(url('/journal/studio' . (isset($post['id']) ? '?id=' . $post['id'] : ''))) ?>" class="panel"><?= csrf_field() ?><input type="hidden" name="action" value="save"><div class="form-grid">
<?php foreach (['title' => ['Story title', 2, 180], 'client_name' => ['Business / client name', 2, 160], 'category' => ['Category', 2, 120]] as $key => [$label, $min, $max]): ?><label class="field<?= $key === 'title' ? ' wide' : '' ?>"><span><?= $label ?></span><input name="<?= $key ?>" required minlength="<?= $min ?>" maxlength="<?= $max ?>" value="<?= e($post[$key]) ?>"></label><?php endforeach; ?>
<label class="field wide"><span>Excerpt</span><textarea name="excerpt" required minlength="10" maxlength="500" rows="3"><?= e($post['excerpt']) ?></textarea></label>
<label class="field wide"><span>Story <small>Plain text · blank lines separate paragraphs</small></span><textarea name="body" required minlength="30" maxlength="20000" rows="14"><?= e($post['body']) ?></textarea></label>
<label class="field wide"><span>Services <small>Separate labels with commas</small></span><input name="services" maxlength="2000" value="<?= e(implode(', ', $post['services'])) ?>"></label>
<label class="field"><span>Accent</span><select name="accent"><?php foreach (['green', 'amber', 'violet', 'pink'] as $accent): ?><option value="<?= $accent ?>"<?= $post['accent'] === $accent ? ' selected' : '' ?>><?= ucfirst($accent) ?></option><?php endforeach; ?></select></label>
<label class="field"><span>Visibility</span><select name="status"><?php foreach (['draft', 'published'] as $status): ?><option value="<?= $status ?>"<?= $post['status'] === $status ? ' selected' : '' ?>><?= ucfirst($status) ?></option><?php endforeach; ?></select></label>
<label class="consent wide"><input type="checkbox" name="featured" value="1"<?= $post['featured'] ? ' checked' : '' ?>><span>Feature this story</span></label></div>
<div class="actions"><button type="submit" class="button">Save story</button><?php if (($post['status'] ?? '') === 'published' && !empty($post['slug'])): ?><a class="button-secondary" href="<?= e(url('/journal/' . $post['slug'])) ?>" target="_blank" rel="noopener">View published story ↗</a><?php endif; ?></div></form>
<?php if (isset($post['id'])): ?><form method="post" action="<?= e(url('/journal/studio?id=' . $post['id'])) ?>" class="panel delete-panel" data-confirm-delete><?= csrf_field() ?><input type="hidden" name="action" value="delete"><h3>Delete story</h3><p class="muted">This permanently deletes this story from the Journal. This action cannot be undone.</p><button type="submit" class="danger-button">Delete this story</button></form><?php endif; ?>
</section></main>