-- MySQL 8 / MariaDB 10.6+. Import once for a NEW installation.
-- PostgreSQL arrays are represented by JSON; PHP handles both.
CREATE TABLE IF NOT EXISTS blog_posts (
 id INT AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(100) NOT NULL UNIQUE,
 title TEXT NOT NULL, client_name TEXT NOT NULL, category TEXT NOT NULL,
 excerpt TEXT NOT NULL, body LONGTEXT NOT NULL, services JSON NOT NULL,
 accent VARCHAR(20) NOT NULL DEFAULT 'green', status VARCHAR(20) NOT NULL DEFAULT 'published',
 featured BOOLEAN NOT NULL DEFAULT false, published_at DATETIME NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS usabime_requests (
 id INT AUTO_INCREMENT PRIMARY KEY, reference VARCHAR(20) NOT NULL UNIQUE,
 full_name TEXT NOT NULL, phone_number TEXT NOT NULL, email TEXT NULL,
 business_name TEXT NOT NULL, business_type TEXT NOT NULL, service_type TEXT NOT NULL,
 business_description TEXT NOT NULL, industry TEXT NOT NULL, location TEXT NOT NULL,
 public_contact TEXT NOT NULL, brand_colors TEXT NOT NULL, asset_links JSON NOT NULL,
 website_references JSON NOT NULL, preferred_timeline TEXT NOT NULL, target_date DATE NULL,
 additional_details TEXT NOT NULL, privacy_accepted BOOLEAN NOT NULL DEFAULT true,
 privacy_accepted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 status VARCHAR(40) NOT NULL DEFAULT 'new', admin_notes TEXT NOT NULL DEFAULT (''),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS usabime_proposals (
 id INT AUTO_INCREMENT PRIMARY KEY, request_id INT NOT NULL UNIQUE, title TEXT NOT NULL,
 introduction TEXT NOT NULL, scope TEXT NOT NULL, currency VARCHAR(24) NOT NULL,
 line_items JSON NOT NULL, payment_terms TEXT NOT NULL, timeline TEXT NOT NULL,
 valid_until VARCHAR(10) NULL, terms TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (request_id) REFERENCES usabime_requests(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS contact_inquiries (
 id INT AUTO_INCREMENT PRIMARY KEY, reference VARCHAR(20) NOT NULL UNIQUE,
 full_name TEXT NOT NULL, email TEXT NOT NULL, phone_number TEXT NOT NULL,
 service VARCHAR(60) NOT NULL, budget TEXT NOT NULL, message TEXT NOT NULL,
 privacy_accepted BOOLEAN NOT NULL DEFAULT true, privacy_accepted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 status VARCHAR(40) NOT NULL DEFAULT 'new', admin_notes TEXT NOT NULL DEFAULT (''),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS security_limits (
 `key` VARCHAR(64) PRIMARY KEY, window_start BIGINT NOT NULL, attempts INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;